# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hypertrophy
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: "hypertrophy-db"
    user: 1000:1000
    ports:
      - 5432:5432
